dict_code = {
    "USA":"us",
    "Italy":"it",
    "Spain":"es",
    "Germany":"de",
    "France":"fr",
    "Iran":"ir",
    "UK":"gb",
    "Switzerland":"ch",
    "Belgium":"be",
    "Netherlands":"nl",
    "Turkey":"tr",
    "S. Korea":"kr",
    "Austria":"at",
    "Canada":"ca",
    "Portugal":"pt",
    "Israel":"il",
    "Brazil":"br",
    "Australia":"au",
    "Norway":"no",
    "Sweden":"se",
    "Czechia":"cz",
    "Ireland":"ie",
    "Malaysia":"my",
    "Denmark":"dk",
    "Chile":"cl",
    "Poland":"pl",
    "Romania":"ro",
    "Luxembourg":"lu",
    "Ecuador":"ec",
    "Japan":"jp",
    "Pakistan":"pk",
    "Russia":"ru",
    "Thailand":"th",
    "Philippines":"ph",
    "Saudi Arabia":"sa",
    "Indonesia":"id",
    "Finland":"fi",
    "South Africa":"za",
    "India":"in",
    "Greece":"gr",
    "Mexico":"mx",
    "Iceland":"is",
    "Panama":"pa",
    "Argentina":"ar",
    "Peru":"pe",
    "Dominican Republic":"do",
    "Singapore":"sg",
    "Colombia":"co",
    "Croatia":"hr",
    "Serbia":"rs",
    "Slovenia":"si",
    "Estonia":"ee",
    "Diamond Princess":"ship-dp",  
    "Qatar":"qa",
    "Hong Kong":"hk",
    "Egypt":"eg",
    "New Zealand":"nz",
    "Iraq":"iq",
    "UAE":"ae", 
    "Algeria":"dz",
    "Morocco":"ma",
    "Ukraine":"ua",
    "Lithuania":"lt",
    "Bahrain":"bh",
    "Hungary":"hu",
    "Armenia":"am",
    "Lebanon":"lb",
    "Latvia":"lv",
    "Bosnia and Herzegovina":"ba",
    "Bulgaria":"bg",
    "Andorra":"ad",
    "Tunisia":"tn",
    "Slovakia":"sk",
    "Costa Rica":"cr",
    "Kazakhstan":"kz",
    "Taiwan":"tw",
    "Uruguay":"uy",
    "Moldova":"md",
    "North Macedonia":"mk",
    "Azerbaijan":"az",
    "Jordan":"jo",
    "Kuwait":"kw",
    "Burkina Faso":"bf",
    "San Marino":"sm",
    "Cyprus":"cy",
    "Réunion":"re",
    "Albania":"al",
    "Vietnam":"vn",
    "Cameroon":"cm",
    "Oman":"om",
    "Afghanistan":"af",
    "Cuba":"cu",
    "Faeroe Islands":"fo",
    "Ivory Coast":"ci", 
    "Senegal":"sn",
    "Uzbekistan":"uz",
    "Malta":"mt",
    "Ghana":"gh",
    "Belarus":"by",
    "Honduras":"hn",
    "Channel Islands":"gb-",
    "Venezuela":"ve",
    "Nigeria":"ng",
    "Mauritius":"mu",
    "Brunei ":"bn",
    "Sri Lanka":"lk",
    "Palestine":"ps",
    "Georgia":"ge",
    "Bolivia":"bo",
    "Cambodia":"kh",
    "Kyrgyzstan":"kg",
    "Guadeloupe":"gp",
    "Montenegro":"me",
    "Martinique":"mq",
    "Trinidad and Tobago":"tt",
    "Mayotte":"yt",
    "DRC":"cd", 
    "Rwanda":"rw",
    "Gibraltar":"gi",
    "Paraguay":"py",
    "Liechtenstein":"li",
    "Kenya":"ke",
    "Aruba":"aw",
    "Bangladesh":"bd",
    "Monaco":"mc",
    "Isle of Man":"im",
    "Madagascar":"mg",
    "French Guiana":"gf",
    "Macao":"mo",
    "Guatemala":"gt",
    "Jamaica":"jm",
    "French Polynesia":"pf",
    "Zambia":"zm",
    "Barbados":"bb",
    "Uganda":"ug",
    "El Salvador":"sv",
    "Togo":"tg",
    "Niger":"ne",
    "Bermuda":"bm",
    "Mali":"ml",
    "Ethiopia":"et",
    "Guinea":"gn",
    "Tanzania":"tz",
    "Congo":"cg",
    "Djibouti":"dj",
    "Maldives":"mv",
    "Gabon":"ga",
    "Saint Martin":"mf",
    "Eritrea":"er",
    "Haiti":"ht",
    "New Caledonia":"nc",
    "Myanmar":"mm",
    "Bahamas":"bs",
    "Cayman Islands":"ky",
    "Dominica":"dm",
    "Equatorial Guinea":"gq",
    "Mongolia":"mn",
    "Curaçao":"cw",
    "Namibia":"na",
    "Syria":"sy",
    "Greenland":"gl",
    "Seychelles":"sc",
    "Grenada":"gd",
    "Laos":"la",
    "Saint Lucia":"lc",
    "Eswatini":"sz",
    "Guyana":"gy",
    "Zimbabwe":"zw",
    "Guinea-Bissau":"gw",
    "Libya":"ly",
    "Mozambique":"mz",
    "Suriname":"sr",
    "Angola":"ao",
    "Antigua and Barbuda":"ag",
    "Saint Kitts and Nevis":"kn",
    "Sudan":"sd",
    "Cabo Verde":"cv",
    "Mauritania":"mr",
    "Benin":"bj",
    "Vatican City":"va",
    "St. Barth":"bl",
    "Sint Maarten":"sx",
    "Nepal":"np",
    "Chad":"td",
    "Fiji":"fj",
    "Montserrat":"ms",
    "Turks and Caicos":"tc",
    "Gambia":"gm",
    "Nicaragua":"ni",
    "Bhutan":"bt",
    "Belize":"bz",
    "Botswana":"bw",
    "British Virgin Islands":"vg",
    "CAR":"cf",
    "Liberia":"lr",
    "Somalia":"so",
    "MS Zaandam":"ship-mz",
    "Anguilla":"ai",
    "Papua New Guinea":"pg",
    "St. Vincent Grenadines":"vc",
    "Timor-Leste":"tl",
    "China":"cn",
    "Sierra Leone":"sl",
    "Caribbean Netherlands":"bq",
    "Burundi":"bi",
    "Total:":"world"
}

# function to return key for any value 
def get_key(val): 
    for key, value in dict_code.items(): 
         if val == value: 
             return key 
  
    return None